
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tacila
 */
public class InterfaceMain extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceMain
     */
    public InterfaceMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrupo1 = new javax.swing.ButtonGroup();
        buttonGrupo2 = new javax.swing.ButtonGroup();
        buttonGrupo3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        j4ocular = new javax.swing.JRadioButton();
        j3ocular = new javax.swing.JRadioButton();
        j2ocular = new javax.swing.JRadioButton();
        j1ocular = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        j5verbal = new javax.swing.JRadioButton();
        j4verbal = new javax.swing.JRadioButton();
        j3verbal = new javax.swing.JRadioButton();
        j2verbal = new javax.swing.JRadioButton();
        j1verbal = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        j6motora = new javax.swing.JRadioButton();
        j5motora = new javax.swing.JRadioButton();
        j4motora = new javax.swing.JRadioButton();
        j3motora = new javax.swing.JRadioButton();
        j2motora = new javax.swing.JRadioButton();
        j1motora = new javax.swing.JRadioButton();
        jBotaoSair = new javax.swing.JButton();
        jBotaoEnviar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCampoDeTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 245, 235));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medico (1).png"))); // NOI18N
        jLabel1.setText("ABERTURA OCULAR DO PACIENTE (O):");

        buttonGrupo1.add(j4ocular);
        j4ocular.setText("Espontânea");
        j4ocular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j4ocularMouseClicked(evt);
            }
        });
        j4ocular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ocularActionPerformed(evt);
            }
        });

        buttonGrupo1.add(j3ocular);
        j3ocular.setText("Ao estímulo verbal");
        j3ocular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j3ocularMouseClicked(evt);
            }
        });
        j3ocular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ocularActionPerformed(evt);
            }
        });

        buttonGrupo1.add(j2ocular);
        j2ocular.setText("À pressão");
        j2ocular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2ocularMouseClicked(evt);
            }
        });

        buttonGrupo1.add(j1ocular);
        j1ocular.setText("Nenhuma");
        j1ocular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1ocularMouseClicked(evt);
            }
        });
        j1ocular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ocularActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medico (1).png"))); // NOI18N
        jLabel2.setText("RESPOSTA VERBAL (V):");

        buttonGrupo2.add(j5verbal);
        j5verbal.setText("Orientado");
        j5verbal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j5verbalMouseClicked(evt);
            }
        });

        buttonGrupo2.add(j4verbal);
        j4verbal.setText("Confuso");
        j4verbal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j4verbalMouseClicked(evt);
            }
        });
        j4verbal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4verbalActionPerformed(evt);
            }
        });

        buttonGrupo2.add(j3verbal);
        j3verbal.setText("Palavras");
        j3verbal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j3verbalMouseClicked(evt);
            }
        });

        buttonGrupo2.add(j2verbal);
        j2verbal.setText("Sons");
        j2verbal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2verbalMouseClicked(evt);
            }
        });
        j2verbal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2verbalActionPerformed(evt);
            }
        });

        buttonGrupo2.add(j1verbal);
        j1verbal.setText("Nenhuma");
        j1verbal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1verbalMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medico (1).png"))); // NOI18N
        jLabel3.setText("RESPOSTA MOTORA (M):");

        buttonGrupo3.add(j6motora);
        j6motora.setText("Obedece a comandos");
        j6motora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j6motoraMouseClicked(evt);
            }
        });

        buttonGrupo3.add(j5motora);
        j5motora.setText("Localizando");
        j5motora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j5motoraMouseClicked(evt);
            }
        });

        buttonGrupo3.add(j4motora);
        j4motora.setText("Flexão normal");
        j4motora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j4motoraMouseClicked(evt);
            }
        });

        buttonGrupo3.add(j3motora);
        j3motora.setText("Flexão anormal");
        j3motora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j3motoraMouseClicked(evt);
            }
        });

        buttonGrupo3.add(j2motora);
        j2motora.setText("Extensão");
        j2motora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2motoraMouseClicked(evt);
            }
        });

        buttonGrupo3.add(j1motora);
        j1motora.setText("Nenhuma");
        j1motora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1motoraMouseClicked(evt);
            }
        });

        jBotaoSair.setBackground(new java.awt.Color(189, 88, 88));
        jBotaoSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBotaoSair.setForeground(new java.awt.Color(255, 255, 255));
        jBotaoSair.setText("Sair");
        jBotaoSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoSairActionPerformed(evt);
            }
        });

        jBotaoEnviar.setBackground(new java.awt.Color(43, 120, 62));
        jBotaoEnviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBotaoEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jBotaoEnviar.setText("Enviar");
        jBotaoEnviar.setAutoscrolls(true);
        jBotaoEnviar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBotaoEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBotaoEnviarMouseClicked(evt);
            }
        });
        jBotaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoEnviarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ESCALA DE COMA DE GASGLOW");
        jLabel4.setFocusTraversalPolicyProvider(true);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngwing.com.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medico (1).png"))); // NOI18N
        jLabel6.setText("DIGITE O NOME DO PACIENTE:");

        jCampoDeTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCampoDeTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jBotaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jBotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j4ocular)
                                    .addComponent(j1ocular))
                                .addGap(18, 18, 18)
                                .addComponent(j3ocular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j2ocular))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j5verbal)
                                    .addComponent(j2verbal))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j1verbal)
                                    .addComponent(j4verbal))
                                .addGap(18, 18, 18)
                                .addComponent(j3verbal))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j6motora)
                                    .addComponent(j3motora))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j5motora)
                                    .addComponent(j2motora))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j1motora)
                                    .addComponent(j4motora)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCampoDeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCampoDeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j4ocular)
                    .addComponent(j3ocular)
                    .addComponent(j2ocular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(j1ocular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j5verbal)
                    .addComponent(j4verbal)
                    .addComponent(j3verbal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2verbal)
                    .addComponent(j1verbal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j6motora)
                    .addComponent(j5motora)
                    .addComponent(j4motora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j3motora)
                    .addComponent(j2motora)
                    .addComponent(j1motora))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j2verbalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2verbalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j2verbalActionPerformed

    private void j4verbalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4verbalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j4verbalActionPerformed

    private void j1ocularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ocularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j1ocularActionPerformed

    private void j4ocularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ocularActionPerformed
      
    }//GEN-LAST:event_j4ocularActionPerformed

    private void jBotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jBotaoSairActionPerformed

    private void j3ocularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ocularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j3ocularActionPerformed

    private void jBotaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotaoEnviarActionPerformed

    private void jBotaoEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBotaoEnviarMouseClicked
        int total;
        total = 0;
        
        if(j4ocular.isSelected()){
            total += 4;
        }
        
        if(j3ocular.isSelected()){
            total += 3;
        }
        
        if(j2ocular.isSelected()){
            total += 2;
        }
        
        if(j1ocular.isSelected()){
            total += 1;
        }
        
        if(j5verbal.isSelected()){
            total += 5;
        }
        
        if(j4verbal.isSelected()){
            total += 4;
        }
        
        if(j3verbal.isSelected()){
            total += 3;
        }
        
        if(j2verbal.isSelected()){
            total += 2;
        }
        
        if(j1verbal.isSelected()){
            total += 1;
        }
        
        if(j6motora.isSelected()){
            total += 6;
        }
        
        if(j5motora.isSelected()){
            total += 5;
        }
        
        if(j4motora.isSelected()){
            total += 4;
        }
        
        if(j3motora.isSelected()){
            total += 3;
        }
        
        if(j2motora.isSelected()){
            total += 2;
        }
        
        if(j1motora.isSelected()){
            total += 1;
        }
        
      
        if(total > 3 && total <= 8){
            JOptionPane.showMessageDialog(null, "Pontuação: "+total);
            JOptionPane.showMessageDialog(null, "O paciente "+jCampoDeTexto.getText()+" tem um trauma grave!");
        }
        else if(total >= 9 && total <= 12){
            JOptionPane.showMessageDialog(null, "Pontuação: "+total);
            JOptionPane.showMessageDialog(null, "O paciente "+jCampoDeTexto.getText()+" tem um trauma moderado!");
        }
        else if(total >= 13 ){
            JOptionPane.showMessageDialog(null, "Pontuação: "+total);
            JOptionPane.showMessageDialog(null, "O paciente "+jCampoDeTexto.getText()+" tem um trauma leve!");
        }
    }//GEN-LAST:event_jBotaoEnviarMouseClicked

    private void jCampoDeTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCampoDeTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCampoDeTextoActionPerformed

    private void j4ocularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4ocularMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Espontânea: O paciente abre os olhos sem a necessidade de estímulo externo.");
    }//GEN-LAST:event_j4ocularMouseClicked

    private void j3ocularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3ocularMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Ao estímulo verbal: O paciente abre os olhos quando é chamado.");
    }//GEN-LAST:event_j3ocularMouseClicked

    private void j2ocularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2ocularMouseClicked
        JOptionPane.showMessageDialog(rootPane, "À pressão: O paciente abre os olhos após pressão na extremidade dos dedos (aumentando progressivamente a intensidade por 10 segundos).");
    }//GEN-LAST:event_j2ocularMouseClicked

    private void j1ocularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1ocularMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Nenhum: O paciente não abre os olhos, apesar de ser fisicamente capaz de abri-los.");
    }//GEN-LAST:event_j1ocularMouseClicked

    private void j5verbalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j5verbalMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Orientado: O paciente consegue responder adequadamente o nome, local e data.");
    }//GEN-LAST:event_j5verbalMouseClicked

    private void j4verbalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4verbalMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Confuso: O paciente consegue conversar em frases, mas não responde corretamente as perguntas de nome, local e data.");
    }//GEN-LAST:event_j4verbalMouseClicked

    private void j3verbalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3verbalMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Palavras: O paciente não consegue falar em frases, mas interage através de palavras isoladas.");
    }//GEN-LAST:event_j3verbalMouseClicked

    private void j2verbalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2verbalMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Sons: O paciente somente produz gemidos.");
    }//GEN-LAST:event_j2verbalMouseClicked

    private void j1verbalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1verbalMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Nenhum: O paciente não produz sons, apesar de ser fisicamente capaz de realizá-los.");
    }//GEN-LAST:event_j1verbalMouseClicked

    private void j6motoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j6motoraMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Obedece a comandos: O paciente cumpre ordens de atividade motora (duas ações) como apertar a mão do profissional e colocar a língua para fora.");
    }//GEN-LAST:event_j6motoraMouseClicked

    private void j5motoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j5motoraMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Localizando: O paciente eleva a mão acima do nível da clavícula em uma tentativa de interromper o estímulo (durante o pinçamento do trapézio ou incisura supraorbitária).");
    }//GEN-LAST:event_j5motoraMouseClicked

    private void j4motoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4motoraMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Flexão normal: a mão do paciente não alcança a fonte do estímulo, mas há uma flexão rápida do braço ao nível do cotovelo e na direção externa ao corpo.");
    }//GEN-LAST:event_j4motoraMouseClicked

    private void j3motoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3motoraMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Flexão anormal: a mão do paciente não alcança a fonte do estímulo, mas há uma flexão lenta do braço na direção interna do corpo.");
    }//GEN-LAST:event_j3motoraMouseClicked

    private void j2motoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2motoraMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Extensão: O paciente consegue realizar uma extensão do braço ao nível do cotovelo.");
    }//GEN-LAST:event_j2motoraMouseClicked

    private void j1motoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1motoraMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Extensão: O paciente não tem resposta motora dos membros superiores e inferiores, apesar de ser fisicamente capaz.");
    }//GEN-LAST:event_j1motoraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGrupo1;
    private javax.swing.ButtonGroup buttonGrupo2;
    private javax.swing.ButtonGroup buttonGrupo3;
    private javax.swing.JRadioButton j1motora;
    private javax.swing.JRadioButton j1ocular;
    private javax.swing.JRadioButton j1verbal;
    private javax.swing.JRadioButton j2motora;
    private javax.swing.JRadioButton j2ocular;
    private javax.swing.JRadioButton j2verbal;
    private javax.swing.JRadioButton j3motora;
    private javax.swing.JRadioButton j3ocular;
    private javax.swing.JRadioButton j3verbal;
    private javax.swing.JRadioButton j4motora;
    private javax.swing.JRadioButton j4ocular;
    private javax.swing.JRadioButton j4verbal;
    private javax.swing.JRadioButton j5motora;
    private javax.swing.JRadioButton j5verbal;
    private javax.swing.JRadioButton j6motora;
    private javax.swing.JButton jBotaoEnviar;
    private javax.swing.JButton jBotaoSair;
    private javax.swing.JTextField jCampoDeTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
